version: '3.4'

services:
  taskstracker.api:
    image: ${DOCKER_REGISTRY-}taskstrackerapi
    build:
      context: .
      dockerfile: TasksTracker.Api/Dockerfile
  mssqlserver:
    container_name: Microsoft.SqlServer
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        MSSQL_SA_PASSWORD: "Password0!"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - tracker-volume:/var/opt/mssql
volumes:
    tracker-volume: