// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasksTracker.Storage;

#nullable disable

namespace TasksTracker.Storage.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TasksTracker.Storage.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("TasksTracker.Storage.TrackerTask", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = new Guid("c3757032-d6d3-4a6c-ac42-9ca11c4b320a"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5182),
                            Name = "Task #1",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("5c3df405-a675-4737-803f-3c3ba197d7e7"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5196),
                            Name = "Task #2",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("eff057ce-122a-45ff-b617-bf4d5562aed6"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5198),
                            Name = "Task #3",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("8204936f-7af6-4cc7-b5d5-c3fe895aa6b7"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5200),
                            Name = "Task #4",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("2c38b672-7fa3-4f99-ac4a-e39d58570b92"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5202),
                            Name = "Task #5",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("f3f8de08-55a5-40b0-8b36-54292695d73d"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5213),
                            Name = "Task #6",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("f0e4d276-e8ac-49a5-b8fa-a18b6c97ac08"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5215),
                            Name = "Task #7",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("ae69b863-ca8d-4e90-9a87-a6226aea5cb9"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5217),
                            Name = "Task #8",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("b75406b3-c505-4ce7-b710-09795f8c9e37"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5219),
                            Name = "Task #9",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("f9bc0dac-2aa6-4340-b338-d73d9e415112"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5221),
                            Name = "Task #10",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("b62dcab0-1aed-43fa-bac0-bbea714c9ef6"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5223),
                            Name = "Task #11",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("c44ef5eb-8bf4-4ac3-b3d9-e5961c18f2ae"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5225),
                            Name = "Task #12",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("b4b1f61c-ed07-4a20-bd40-ce6beda92fe4"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5227),
                            Name = "Task #13",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("1f302255-db2b-41c1-8adb-c7fcf4c65025"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5231),
                            Name = "Task #14",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("2a3f6db0-0359-4bee-8457-dd8ae92650b3"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5232),
                            Name = "Task #15",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("6f3b07fd-272d-4dda-8d22-3120c00cb907"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5234),
                            Name = "Task #16",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("4e71e6c8-56a0-4e75-9706-236d070975b3"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5236),
                            Name = "Task #17",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("7f3c4489-852b-42a3-aa4b-3e4400103384"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5238),
                            Name = "Task #18",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("fa538093-d3e1-4699-a1b6-a829d268be9e"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5240),
                            Name = "Task #19",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("acf36704-ee54-4b95-907a-666dc281fcde"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5242),
                            Name = "Task #20",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("3b67362b-9b8e-4f27-b2cd-8ab83aa5d62f"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5244),
                            Name = "Task #21",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("c657f8d4-289a-47fc-a9cf-c436cccb9dc9"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5247),
                            Name = "Task #22",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("22d719fe-69b2-4c5f-bfb4-ec2ed3fa915c"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5249),
                            Name = "Task #23",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("42435191-efb9-46af-b6e4-f8d520b52bce"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5250),
                            Name = "Task #24",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("a91af55d-d68c-444f-bef0-a83f8b2a3540"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5252),
                            Name = "Task #25",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("371e48ee-f39d-463f-9b86-0c68fec3c3b1"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5254),
                            Name = "Task #26",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("3b60f965-0272-49c6-81ae-c65b4f1cbb4b"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5255),
                            Name = "Task #27",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("b6ff5fb3-1176-45cd-8187-48939bcbf794"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5257),
                            Name = "Task #28",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("f172fc25-7bc8-4d2b-a2b0-2ae1ac584dcd"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5259),
                            Name = "Task #29",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("7587336f-40c7-45a5-925a-ba94fafde703"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5262),
                            Name = "Task #30",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("6647f234-45f2-495b-8445-e77f586e706b"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5264),
                            Name = "Task #31",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("80dfbb0b-2636-447a-b4ed-0214451eef7e"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5266),
                            Name = "Task #32",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("dcacd144-f54e-46e3-8cb5-aa74d47dc853"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5268),
                            Name = "Task #33",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("d66282a2-4aab-4881-82f7-656354d815fd"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5270),
                            Name = "Task #34",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("849980fd-e593-4cec-9d94-c443fbcbc1fc"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5295),
                            Name = "Task #35",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("e95cbdfa-1c4b-416d-902e-fc809049de93"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5297),
                            Name = "Task #36",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("11572be4-842d-4908-876f-63d4e7d60005"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5298),
                            Name = "Task #37",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("ba9563b5-37a3-41f4-9f38-3156f7e22fbf"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5302),
                            Name = "Task #38",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("04f5c36f-6510-47d6-81e6-8cdba2b7c14e"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5304),
                            Name = "Task #39",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("9e51bde2-7a37-4968-a0fd-8c6616ef6f20"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5305),
                            Name = "Task #40",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("0652e5bf-b798-47d7-a612-61e41a6224e5"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5307),
                            Name = "Task #41",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("d2933fc2-7a72-49d8-a421-c638f6549efb"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5309),
                            Name = "Task #42",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("8e2a4354-0798-4511-8ddf-73b22dfe8fdd"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5311),
                            Name = "Task #43",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("f5c42aa2-4b91-4083-bf31-c669e5f959d0"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5312),
                            Name = "Task #44",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("ce30e8ff-e9cf-453f-ab74-3227aa9a5d0a"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5314),
                            Name = "Task #45",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("1cb28e2e-79de-4e87-9b6c-7489b824cb25"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5317),
                            Name = "Task #46",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("ed1ef4e3-b1b6-4aa4-a6f1-9a4974259288"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5319),
                            Name = "Task #47",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("447b9a06-539b-43ae-9a84-ff4725096158"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5321),
                            Name = "Task #48",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("5fafaacd-aed1-4b7e-8337-803b9127cbcf"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5323),
                            Name = "Task #49",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("ef1820b5-f06d-4a6b-9e19-7834c898c668"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5324),
                            Name = "Task #50",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("d6397912-ab1d-474f-b1d2-2650407e61bc"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5326),
                            Name = "Task #51",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("23ba9de0-55cd-4581-833a-5fb724a990a5"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5328),
                            Name = "Task #52",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("0abc8693-5d70-48fd-807b-39a0cb39f7d3"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5330),
                            Name = "Task #53",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("2daffb60-a5cb-4ab7-9b1b-24bf6c28149d"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5333),
                            Name = "Task #54",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("8582daae-6735-4fc5-a64a-5286466160d4"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5335),
                            Name = "Task #55",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("0f88a9f0-ddd1-47ea-8fc0-5f7e4ef26003"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5337),
                            Name = "Task #56",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("cd705024-f56e-4f99-b2a0-617842c70e30"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5339),
                            Name = "Task #57",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("cd8a3d89-815b-4c18-a2ac-511801b216ef"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5340),
                            Name = "Task #58",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("8653f92a-4a92-48e0-9292-04ff9a821e4d"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5342),
                            Name = "Task #59",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("081d93ba-237d-460b-a965-355097b60513"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5344),
                            Name = "Task #60",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("60a264df-eacd-4752-a5c5-9eac69c54d0c"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5346),
                            Name = "Task #61",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("0feea68f-66f4-42ae-b128-b532b849ec9c"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5349),
                            Name = "Task #62",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("481d253c-7151-41f9-8cbc-8215e9989335"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5350),
                            Name = "Task #63",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("62404a9f-c786-48b0-8349-eb799f035f8a"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5352),
                            Name = "Task #64",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("57960fe7-1b4a-4766-aa43-9f1fad452334"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5354),
                            Name = "Task #65",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("61cf5c43-cd6f-4773-8187-5f85b5990f32"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5357),
                            Name = "Task #66",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("2e1d2ce2-86b5-41a6-abc1-c3317b0d4858"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5359),
                            Name = "Task #67",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("6b8a7c4e-e939-451d-8dc3-59270573bb0f"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5360),
                            Name = "Task #68",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("e4a9627d-8e8f-4f06-b977-9ab709414c7e"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5362),
                            Name = "Task #69",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("08ba1b45-6a93-472f-9e0c-7d768fa17e6b"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5365),
                            Name = "Task #70",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("3bfa0b04-bcb1-40b1-868a-859713e4caf5"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5367),
                            Name = "Task #71",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("70cc0554-b28a-443a-aeb1-b0f1613bbea3"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5369),
                            Name = "Task #72",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("43e6aba3-c1c3-4b0e-878c-f985d77cab33"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5370),
                            Name = "Task #73",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("f2518efb-6640-4d63-9773-88841f833e77"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5372),
                            Name = "Task #74",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("5ddd29eb-3828-4c6d-922b-204ce53b1311"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5374),
                            Name = "Task #75",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("403b54ec-bd5a-4c6d-ab17-0ed2ca40264d"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5376),
                            Name = "Task #76",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("8ec37d81-e250-4b8c-b2cf-48997bb165c4"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5397),
                            Name = "Task #77",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("2a9a5784-37a1-40f3-9c68-fe9bb1157aa5"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5400),
                            Name = "Task #78",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("bdee83d1-ad59-4d78-826f-616021117305"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5402),
                            Name = "Task #79",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("82528760-f445-49a7-aa57-963941ac7f62"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5403),
                            Name = "Task #80",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("705b621e-dfd9-4aa7-9edf-5bc111f7d903"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5405),
                            Name = "Task #81",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("5567fb1e-ad35-48bb-8a44-699c8f023773"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5407),
                            Name = "Task #82",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("a96514f6-2b68-476a-9d36-03272bfe1437"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5409),
                            Name = "Task #83",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("2fdd90aa-06e7-4c6f-ae30-c324bae697d5"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5410),
                            Name = "Task #84",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("9e869010-1105-4901-86ec-3ce9b0aa5dcb"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5412),
                            Name = "Task #85",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("b7d939fd-468e-44cf-bf44-4b47e53d18b8"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5415),
                            Name = "Task #86",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("17a621e7-335c-4dee-a4e4-8946314ae29a"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5417),
                            Name = "Task #87",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("24461e16-acb0-47e8-b099-21e4776e709b"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5419),
                            Name = "Task #88",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("6c34db21-9ab0-465e-a1e5-4abae9d46553"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5420),
                            Name = "Task #89",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("fe1252cf-901c-424f-8728-490b9e7685af"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5422),
                            Name = "Task #90",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("0c4fdab0-0622-494f-a598-4738b0543e08"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5424),
                            Name = "Task #91",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("32ca1da3-c6af-469d-913d-a3497f47618f"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5426),
                            Name = "Task #92",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("f375b603-3fcb-4755-bad1-170800269196"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5427),
                            Name = "Task #93",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("a8d10736-52a4-4135-87a2-9bc1ee4160ab"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5431),
                            Name = "Task #94",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("c587d65c-f785-4916-a470-138a3ea65e9c"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5432),
                            Name = "Task #95",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("49d16065-b47f-4cc2-bdba-34d100823113"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5434),
                            Name = "Task #96",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("2cfae9cd-c43b-46d2-958f-13dca70d5063"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5436),
                            Name = "Task #97",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("50ced3ef-84de-4ddc-803d-67fb8f6e85c1"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5438),
                            Name = "Task #98",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("ba846ff2-5eb1-42be-9020-c2e0c959a0cd"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5439),
                            Name = "Task #99",
                            State = 0
                        },
                        new
                        {
                            TaskId = new Guid("36175191-4525-422e-b7e4-01d9c44bc3af"),
                            CreatedAt = new DateTime(2022, 8, 18, 22, 40, 5, 795, DateTimeKind.Local).AddTicks(5441),
                            Name = "Task #100",
                            State = 0
                        });
                });

            modelBuilder.Entity("TasksTracker.Storage.Attachment", b =>
                {
                    b.HasOne("TasksTracker.Storage.TrackerTask", null)
                        .WithMany("Attachments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TasksTracker.Storage.TrackerTask", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
